version: '2.1'
services:
  db:
    container_name: jtl-reporter-db
    build:
      context: ./src/db/
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  migration:
    container_name: jtl-reporter-migration
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
        - DATABASE_URL=postgres://postgres@db/jtl_report
    command: npm run migrate up
    depends_on:
      db:
        condition: service_healthy