version: '3.6'
services:
  db:
    container_name: jtl-reporter-db-test
    build:
      context: ./src/db/
      dockerfile: Dockerfile
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  migration:
    container_name: jtl-reporter-migration
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
        - WAIT_HOSTS=db:5432
        - DATABASE_URL=postgres://postgres:password@db/jtl_report
    command: sh -c "/wait && npm run migrate up"
    depends_on:
      - db
  
