name: Integration Tests
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Docker-compose
        run: docker-compose --file docker-compose.testing.yaml up --build -d
      - name: Run ESLint
        run: npm run integration-tests

