name: Static Analysis
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npm run lint
      - name: Run TS check
        run: npm run ts-check
